---
version: "3"
services:
  brscan-skey:
    image: vet5lqplpecmpnqb/brscan-skey
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./onedrive.refresh_token:/app/bash-onedrive-upload/.refresh_token
      - ./evernote.access_token:/app/up2ever/.access_token
    privileged: true
    network_mode: host